### ISSUE TITLE
Error when running example.py

### ISSUE THREAD

**Issue by BelugaWhale** [AshwinPathi/claude#2]
```
e:/repositories/Claude_test2/example.py    
Listing current conversations:
[{'created_at': '2023-07-18T12:31:00.542947+00:00',
  'name': 'Hello greeting',
  'summary': '',
  'updated_at': '2023-07-18T12:31:02.300568+00:00',
  'uuid': 'f66541ef-793d-48d8-b575-c2b9e6e27365'}]

Traceback (most recent call last):
  File "e:\repositories\Claude_test2\example.py", line 94, in <module>
    main()
  File "e:\repositories\Claude_test2\example.py", line 39, in main
    conversation_uuid = claude_obj.start_new_conversation("New Conversation", "Hi Claude!")
  File "e:\repositories\Claude_test2\claude\claude_wrapper.py", line 80, in start_new_conversation
    send_init_message_result = self._client.send_message(
  File "e:\repositories\Claude_test2\claude\claude_client.py", line 58, in send_message
    for elem in self._send_message(
  File "e:\repositories\Claude_test2\claude\claude_client.py", line 241, in _send_message
    for streamed_data_chunk in custom_requests.sse(
  File "e:\repositories\Claude_test2\claude\custom_requests.py", line 68, in sse
    client = sseclient.SSEClient(response)
  File "C:\Users\Ahmed\anaconda3\lib\site-packages\sseclient.py", line 48, in __init__
    self._connect()
  File "C:\Users\Ahmed\anaconda3\lib\site-packages\sseclient.py", line 56, in _connect
    self.resp = requester.get(self.url, stream=True, **self.requests_kwargs)
  File "C:\Users\Ahmed\anaconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Ahmed\anaconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Ahmed\anaconda3\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "C:\Users\Ahmed\anaconda3\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\Ahmed\anaconda3\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Ahmed\anaconda3\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '<http.client.HTTPResponse object at 0x0000019644DF8760>': No scheme supplied. Perhaps you meant http://<http.client.HTTPResponse object at 0x0000019644DF8760>?
```

**Comment by AshwinPathi** [comment]
@BelugaWhale I changed the `setup.py` file to reflect the correct `sseclient` package. Try reinstalling and running it again, or follow the above comment to see if it works.
